services:
  - type: web
    name: comis
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    region: oregon
    branch: main
    autoDeploy: true